name: Coding Monkey
# markdown: redcarpet
markdown: kramdown
highligher: 'pygments'
description: "A coding monkey, who is passionate in algorithm and machine learning, hoping one day to become a coding machine."
url: "pyemma.github.io"
permalink: /posts/:title
